#!/usr/bin/env python3
"""
LAS/LAZ file validator using laspy
Validates LAS files generated by CompactMapper
"""

import argparse
import sys
import laspy


def validate_las(filepath):
    """Open and validate a LAS file, printing basic information."""
    try:
        with laspy.open(filepath) as fh:
            print(f"File: {filepath}")
            print(f"LAS Version: {fh.header.version.major}.{fh.header.version.minor}")
            print(f"Point Format: {fh.header.point_format.id}")
            print(f"Point Count: {fh.header.point_count}")

            # Read the data
            las = fh.read()

            # Display bounds
            print(f"\nBounding Box:")
            print(f"  X: {fh.header.x_min:.3f} to {fh.header.x_max:.3f}")
            print(f"  Y: {fh.header.y_min:.3f} to {fh.header.y_max:.3f}")
            print(f"  Z: {fh.header.z_min:.3f} to {fh.header.z_max:.3f}")

            # Display scale
            print(f"\nScale Factors:")
            print(f"  X: {fh.header.x_scale}")
            print(f"  Y: {fh.header.y_scale}")
            print(f"  Z: {fh.header.z_scale}")

            # Check RGB colors if available
            if hasattr(las, 'red') and hasattr(las, 'green') and hasattr(las, 'blue'):
                print(f"\nRGB Colors Available: Yes")
                print(f"  Sample point 0 RGB: ({las.red[0]}, {las.green[0]}, {las.blue[0]})")
                if len(las.points) > 1:
                    print(f"  Sample point 1 RGB: ({las.red[1]}, {las.green[1]}, {las.blue[1]})")
            else:
                print(f"\nRGB Colors Available: No")

            # System ID and Generating Software
            print(f"\nSystem ID: {fh.header.system_identifier}")
            print(f"Generating Software: {fh.header.generating_software}")

            print(f"\n✅ File is valid and readable!")
            return True

    except Exception as e:
        print(f"❌ Error reading file: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(
        description='Validate LAS/LAZ files generated by CompactMapper',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python validate/test.py output/sample1.las
  python validate/test.py -f output/converted.las
        """
    )

    parser.add_argument(
        'filepath',
        nargs='?',
        help='Path to LAS/LAZ file to validate'
    )

    parser.add_argument(
        '-f', '--file',
        dest='file_path',
        help='Path to LAS/LAZ file (alternative to positional argument)'
    )

    args = parser.parse_args()

    # Get file path from either positional or named argument
    filepath = args.filepath or args.file_path

    if not filepath:
        parser.print_help()
        sys.exit(1)

    # Validate the file
    success = validate_las(filepath)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
